# This is a basic workflow to help you get started with Actions

name: Project CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - main
    paths:
      - project/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  project-testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          
      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
  
      - name: Install Jayvee
        run: |
            npm install -g @jvalue/jayvee-interpreter
            
      - name: Install git-secrets
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets && sudo make install
          
      - name: Run pipeline with secrets
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLEUSERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLEKEY }}
        run: |
          bash ./project/tests.sh $KAGGLEUSERNAME $KAGGLEKEY
      
